### ISSUE TITLE
hello !

### ISSUE THREAD

**Issue by Hepic** [anshbansal/general#1]
I saw a post you done in quora, about github search. I see that you have contribute enough so I would like to ask you,what did you do and you find interesting projects?
Also I was wondering if you have any current project and I can contribute. Thank you for your time!

**Comment by anshbansal** [comment]
@Hepic I am contributing to the projects that I am using. The main contributions that I did were documentation fixes. e.g. I am using a programming language Groovy and I read the docs. I found some mistakes so I sent Pull Requests. 

If I find time and something that I can fix I try to do that.

Regarding current projects I don't have any that I am working on. I am currently busy in my job. In the meantime I am learning a new language - Clojure. Just beginning though.

In case you are starting you can try following https://www.reddit.com/r/programming Here you may find interesting things.
